rg_name      = "rg-prod"
vnet_name    = "vnet-prod"
vm_name      = "vm-prod"
location     = "centralus"
kv_name      = "demokeyvault9834"
kv_resource_group_name   = "demorg9834"
storage_account_name = "demostorage9834"
container_name       = "tfstate"
