rg_name      = "rg-test"
vnet_name    = "vnet-test"
vm_name      = "vm-test"
location     = "eastus2"
kv_name      = "demokeyvault9834"
kv_resource_group_name   = "demorg9834"
storage_account_name = "demostorage9834"
container_name       = "tfstate"
