rg_name      = "rg-dev"
vnet_name    = "vnet-dev"
vm_name      = "vm-dev"
location     = "eastus"
kv_name      = "demokeyvault9834"
kv_resource_group_name   = "demorg9834"
storage_account_name = "demostorage9834"
container_name       = "tfstate"
